name: CI/CD

on: 
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: docker
    runs-on: ubuntu-latest
    steps:
      - name: checkout scm
        uses: actions/checkout@v2
      - name: docker/build-push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: hacksore/hks
          tags: latest
      - name: docker/run
        run: |
          docker run hacksore/hks:latest 'hyundai' 'list' '99cfff84-f4e2-4be8-a5ed-e5b755eb6581' > hyundai.list.txt
      - name: docker/run
        run: 
          docker run hacksore/hks:latest 'kia' 'list' '693a33fa-c117-43f2-ae3b-61a02d24f417' > kia.list.txt
      - uses: actions/upload-artifact@v2
        with:
          name: hyundai.stamps
          path: hyundai.list.txt
      - uses: actions/upload-artifact@v2
        with:
          name: kia.stamps
          path: kia.list.txt