name: CI/CD

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    name: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v3
      - name: Build and push image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64
          push: true
          context: .
          build-args: "--progress=plain"
          tags: hacksore/hks:${{ github.ref_name }}
